### ISSUE TITLE
Organizar Cronogramas

### ISSUE THREAD

**Issue by veluaru** [calidadudea/Admins#2]
Yo como administrador quiero organizar los cronogramas del proyecto y los equipos para llevar control de cuando se realizan las actividades.

- [x] **Definir fechas de reuniones con cliente:** Yo como administrador quiero definir cada una de las fechas de las reuniones con el cliente para tener una constante retroalimentación del proyecto con el cliente.

- [x] **Definir reuniones con cada equipo:** Yo como administrador quiero definir las fechas de las reuniones con cada equipo para tener una constante retroalimentación del proyecto y avances de cada equipo.

- [x] **Definir fechas de entregas:** Yo como administrador quiero definir fechas de entregas de los avances de cada equipo para controlar que se realicen cada una de las tareas asignadas.

**Comment by breakermoob** [comment]
[Cronograma de Fechas con equipos.v1f.pdf](https://github.com/calidadudea/Admins/files/3719971/Cronograma.de.Fechas.con.equipos.v1f.pdf)
[Cronograma de Fechas con los clientes.vf1.pdf](https://github.com/calidadudea/Admins/files/3719972/Cronograma.de.Fechas.con.los.clientes.vf1.pdf)
[Fechas de Entrega.v1f.pdf](https://github.com/calidadudea/Admins/files/3719973/Fechas.de.Entrega.v1f.pdf)
#9 #8 #7
