### ISSUE TITLE
Administrar Presupuestos y Recursos

### ISSUE THREAD

**Issue by veluaru** [calidadudea/Admins#3]
Yo como administrador quiero administrar los presupuestos y recursos del proyecto para destinar este de acuerdo a las necesidades del proyecto y los equipos.

- [ ] **Analizar presupuesto necesario para la aplicación:** Yo como administrador tengo que hacer un análisis sobre todos los gastos proyectados según los reportes de las necesidades de todas las areas de interes.

- [ ] **Destinar presupuesto a cada equipo:** Yo como administrador quiero que cada equipo trabaje bajo un presupuesto y que no se salga de este, teniendo en cuenta que existan retrasos en las entregas o necesidad de conseguir más recursos.

- [ ] **Procesar peticiones de recursos:** Yo como administrador  quiero recolectar las peticiones de recursos de los trabajadores para suministrarles lo necesario y mejorar el desempeño de trabajo.

**Comment by breakermoob** [comment]
[Formato Licitación de Recursos - Hoja 1.v1f.pdf](https://github.com/calidadudea/Admins/files/3719986/Formato.Licitacion.de.Recursos.-.Hoja.1.v1f.pdf)
[Nomina Prestacion de Servicios.v1f.pdf](https://github.com/calidadudea/Admins/files/3719987/Nomina.Prestacion.de.Servicios.v1f.pdf)
[Reporte de Pagos.v1f.pdf](https://github.com/calidadudea/Admins/files/3719988/Reporte.de.Pagos.v1f.pdf)
#18 #19 #20
