### ISSUE TITLE
Recolectar y Reportar Información

### ISSUE THREAD

**Issue by veluaru** [calidadudea/Admins#4]
Yo como administrador quiero recolectar, organizar y reportar los avances del proyecto a los coordinadores para hacer retroalimentación del proyecto.

- [ ] **Informar a equipos sus respectivas tareas:** Yo como administrador tengo que reportar cambios a los equipos según las necesidades del proyecto que afecten las fechas de entrega o las áreas de trabajo.

- [ ] **Recolectar los avances en la fecha establecida:** Yo como administrador quiero un formato para presentar avances y cambios al proyecto según cada área de trabajo.

- [ ] **Reportar avances a coordinadores:** Yo como administrador desarrollo informes periódicos para informar a los coordinadores sobre los avances del proyecto.

- [ ] **Documentar avances de los equipos:** Yo como administrador debo documentar el avance de cada equipo en las fechas establecidas para llevar control de todos los progresos del proyecto.

**Comment by breakermoob** [comment]
En el mismo formato se acoplaron los siguientes : Informar a equipos sus respectivas tareas, Recolectar los avances en la fecha establecida
[Formato de trabajo por equipos.v1f.xlsx](https://github.com/calidadudea/Admins/files/3719995/Formato.de.trabajo.por.equipos.v1f.xlsx)
#14 #15 #16 #17
