### ISSUE TITLE
Crear Formatos

### ISSUE THREAD

**Issue by veluaru** [calidadudea/Admins#5]
Yo como administrador quiero crear formatos para las diferentes entregas y peticiones, y de esta forma llevar una documentación y un seguimiento del proyecto de una manera organizada.

- [ ] **Crear formato de entrega de avances de cada equipo:** Yo como administrador quiero crear un formato en el cual cada equipo entregará sus avances en fechas establecidas, con el fin de obtener y clasificar la información de una manera más organizada.

- [ ] **Crear formato para licitar recursos:** Yo como administrador quiero diseñar un formato en el cual cada equipo demandará los recursos que necesita, con el fin de solicitar estos recursos a los coordinadores y facilitarle a cada grupo. 

- [ ] **Crear formato de documentación del estado del proyecto:** Yo como administrador quiero crear un formato para documentar el estado en el que se encuentra el proyecto que contenga los tiempos y avances de cada equipo, para reportar la información de manera más ordenada.

- [ ] **Crear formato de preguntas:** Yo como administrador quiero diseñar un formato de preguntas con la finalidad de que cada equipo registre sus inquietudes de una manera más organizada  y así evitar pérdida de información

**Comment by breakermoob** [comment]
[Formato Licitación de Recursos - Hoja 1.v1f.pdf](https://github.com/calidadudea/Admins/files/3720005/Formato.Licitacion.de.Recursos.-.Hoja.1.v1f.pdf)
[Proceso de Entrega de Peticiones - Hoja 1.v1f.pdf](https://github.com/calidadudea/Admins/files/3720006/Proceso.de.Entrega.de.Peticiones.-.Hoja.1.v1f.pdf)
[Formato de Preguntas - Hoja 1.v1f.pdf](https://github.com/calidadudea/Admins/files/3720007/Formato.de.Preguntas.-.Hoja.1.v1f.pdf)
[Formato de trabajo por equipos.v1f.pdf](https://github.com/calidadudea/Admins/files/3720008/Formato.de.trabajo.por.equipos.v1f.pdf)
#13 #10 #11 #12
